modLoader="javafml"
loaderVersion="[52,)"  # Forge 52+ (pour 1.21.1 - 52.1.0)

license="MIT"

[[mods]]
modId="jojomod"
version="0.1-1.21.1"
displayName="A Jojo Mod"
authors="Captain"
description='''A Jojo Mod'''

[[dependencies.JojoMod]]
modId="forge"
mandatory=true
versionRange="[52,)"
ordering="NONE"
side="BOTH"

[[dependencies.JojoMod]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
